version: '3.8'
services:
  MC-Route:
    image: ubuntu
    volumes:
      - /home/${USER}/add-route.sh:/add-route.sh
    networks:
      - minecraft
    entrypoint: "/add-route.sh '${SERVER}.zackattack.games' ${SERVER}"
  $SERVER: #change this
    image: itzg/minecraft-server:latest
    volumes:
      - /opt/minecraft/${SERVER}:/data
      - /home/${USER}/add-route.sh:/add-route.sh
    networks:
      - minecraft
    environment:
      EULA: "true"
networks:
  minecraft:
    external: true