version: '3.8'

services:
  mc-router:
    image: itzg/mc-router:latest
    ports:
      - "25565:25565"
      - "127.0.0.1:25560:25560"
    networks:
      - minecraft
    environment:
      API_BINDING: ":25560"
      ROUTES_CONFIG: "/routes.txt"
    volumes:
      - /opt/minecraft/router/routes.txt:/routes.txt

networks:
  minecraft:
    external: true