version: "3.8"

services:
  server-name:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    volumes:
      - /opt/minecraft/${SERVER}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.minecraft-${SERVER}.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft-${SERVER}.service=HostSNI(`minecraft-${SERVER}.zackattack.games`)"
      - "traefik.tcp.routers.minecraft-${SERVER}-secure.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft-${SERVER}-secure.rule=HostSNI(`minecraft-${SERVER}.zackattack.games`)"
      - "traefik.tcp.routers.minecraft-${SERVER}-secure.tls=true"
      - "traefik.tcp.routers.minecraft-${SERVER}-secure.service=minecraft-${SERVER}"
      - "traefik.docker.network=proxy"
      - "traefik.tcp.services.minecraft-${SERVER}.loadbalancer.server.port=25565"
      - "traefik.tcp.routers.minecraft-${SERVER}.tls.passthrough=true"
      - "traefik.tcp.routers.minecraft-${SERVER}-secure.tls.passthrough=true"
    networks:
      - proxy
    
networks:
  proxy:
    external: true